### ISSUE TITLE
No support to ingress to dkron-server

### ISSUE THREAD

**Issue by jannotti-glaucio** [distribworks/dkron-helm#12]
Does the helm chart support the creation of an ingress to the dkron-server web interface (port 8080) ?

I tried to create an ingress, but it is not working. 
Can anyone help me to understand what is wrong?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dkron-server
  annotations:
    ...
  labels:
    app: dkron-server
spec:
  ingressClassName: alb
  rules:
    - host: dkron.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dkron
                port:
                  number: 8080
```
